version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ProdutosDB
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ProdutosDB
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jc-network

volumes:
  postgres-data:

networks:
  jc-network:
    driver: bridge